import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

part 'select_country_cubit_state.dart';

class CountryCodeAndName {
  final String countryCode;
  final String countryName;
  CountryCodeAndName(this.countryCode, this.countryName);
}

class SelectCountryCubit extends Cubit<SelectCountryCubitState> {
  SelectCountryCubit()
      : super(SelectCountryCubitState(
          countryCode: allCountryCode,
          countryName: "All",
        ));

  void selectCountry(String emoji) {
    emit(SelectCountryCubitState(
      countryCode:
          emojiToCountryCodeAndName[emoji]?.countryCode ?? allCountryCode,
      countryName: emojiToCountryCodeAndName[emoji]?.countryName ?? "All",
    ));
  }

  static String allCountryCode = 'ALL';
  static Map<String, CountryCodeAndName> emojiToCountryCodeAndName = {
    "🌎": CountryCodeAndName(allCountryCode, "All"),
    "🇦🇩": CountryCodeAndName("AD", "Andorra"),
    "🇦🇪": CountryCodeAndName("AE", "United Arab Emirates"),
    "🇦🇫": CountryCodeAndName("AF", "Afghanistan"),
    "🇦🇬": CountryCodeAndName("AG", "Antigua & Barbuda"),
    "🇦🇮": CountryCodeAndName("AI", "Anguilla"),
    "🇦🇱": CountryCodeAndName("AL", "Albania"),
    "🇦🇲": CountryCodeAndName("AM", "Armenia"),
    "🇦🇴": CountryCodeAndName("AO", "Angola"),
    "🇦🇷": CountryCodeAndName("AR", "Argentina"),
    "🇦🇸": CountryCodeAndName("AS", "American Samoa"),
    "🇦🇹": CountryCodeAndName("AT", "Austria"),
    "🇦🇺": CountryCodeAndName("AU", "Australia"),
    "🇦🇼": CountryCodeAndName("AW", "Aruba"),
    "🇦🇽": CountryCodeAndName("AX", "Åland Islands"),
    "🇦🇿": CountryCodeAndName("AZ", "Azerbaijan"),
    "🇧🇦": CountryCodeAndName("BA", "Bosnia & Herzegovina"),
    "🇧🇧": CountryCodeAndName("BB", "Barbados"),
    "🇧🇩": CountryCodeAndName("BD", "Bangladesh"),
    "🇧🇪": CountryCodeAndName("BE", "Belgium"),
    "🇧🇫": CountryCodeAndName("BF", "Burkina Faso"),
    "🇧🇬": CountryCodeAndName("BG", "Bulgaria"),
    "🇧🇭": CountryCodeAndName("BH", "Bahrain"),
    "🇧🇮": CountryCodeAndName("BI", "Burundi"),
    "🇧🇯": CountryCodeAndName("BJ", "Benin"),
    "🇧🇱": CountryCodeAndName("BL", "St. Barthélemy"),
    "🇧🇲": CountryCodeAndName("BM", "Bermuda"),
    "🇧🇳": CountryCodeAndName("BN", "Brunei"),
    "🇧🇴": CountryCodeAndName("BO", "Bolivia"),
    "🇧🇶": CountryCodeAndName("BQ", "Caribbean Netherlands"),
    "🇧🇷": CountryCodeAndName("BR", "Brazil"),
    "🇧🇸": CountryCodeAndName("BS", "Bahamas"),
    "🇧🇹": CountryCodeAndName("BT", "Bhutan"),
    "🇧🇻": CountryCodeAndName("BV", "Bouvet Island"),
    "🇧🇼": CountryCodeAndName("BW", "Botswana"),
    "🇧🇾": CountryCodeAndName("BY", "Belarus"),
    "🇧🇿": CountryCodeAndName("BZ", "Belize"),
    "🇨🇦": CountryCodeAndName("CA", "Canada"),
    "🇨🇨": CountryCodeAndName("CC", "Cocos (Keeling) Islands"),
    "🇨🇩": CountryCodeAndName("CD", "Congo - Kinshasa"),
    "🇨🇫": CountryCodeAndName("CF", "Central African Republic"),
    "🇨🇬": CountryCodeAndName("CG", "Congo - Brazzaville"),
    "🇨🇭": CountryCodeAndName("CH", "Switzerland"),
    "🇨🇮": CountryCodeAndName("CI", "Côte d'Ivoire"),
    "🇨🇰": CountryCodeAndName("CK", "Cook Islands"),
    "🇨🇱": CountryCodeAndName("CL", "Chile"),
    "🇨🇲": CountryCodeAndName("CM", "Cameroon"),
    "🇨🇳": CountryCodeAndName("CN", "China"),
    "🇨🇴": CountryCodeAndName("CO", "Colombia"),
    "🇨🇷": CountryCodeAndName("CR", "Costa Rica"),
    "🇨🇺": CountryCodeAndName("CU", "Cuba"),
    "🇨🇻": CountryCodeAndName("CV", "Cape Verde"),
    "🇨🇼": CountryCodeAndName("CW", "Curaçao"),
    "🇨🇽": CountryCodeAndName("CX", "Christmas Island"),
    "🇨🇾": CountryCodeAndName("CY", "Cyprus"),
    "🇨🇿": CountryCodeAndName("CZ", "Czechia"),
    "🇩🇪": CountryCodeAndName("DE", "Germany"),
    "🇩🇯": CountryCodeAndName("DJ", "Djibouti"),
    "🇩🇰": CountryCodeAndName("DK", "Denmark"),
    "🇩🇲": CountryCodeAndName("DM", "Dominica"),
    "🇩🇴": CountryCodeAndName("DO", "Dominican Republic"),
    "🇩🇿": CountryCodeAndName("DZ", "Algeria"),
    "🇪🇨": CountryCodeAndName("EC", "Ecuador"),
    "🇪🇪": CountryCodeAndName("EE", "Estonia"),
    "🇪🇬": CountryCodeAndName("EG", "Egypt"),
    "🇪🇭": CountryCodeAndName("EH", "Western Sahara"),
    "🇪🇷": CountryCodeAndName("ER", "Eritrea"),
    "🇪🇸": CountryCodeAndName("ES", "Spain"),
    "🇪🇹": CountryCodeAndName("ET", "Ethiopia"),
    "🇫🇮": CountryCodeAndName("FI", "Finland"),
    "🇫🇯": CountryCodeAndName("FJ", "Fiji"),
    "🇫🇰": CountryCodeAndName("FK", "Falkland Islands"),
    "🇫🇲": CountryCodeAndName("FM", "Micronesia"),
    "🇫🇴": CountryCodeAndName("FO", "Faroe Islands"),
    "🇫🇷": CountryCodeAndName("FR", "France"),
    "🇬🇦": CountryCodeAndName("GA", "Gabon"),
    "🇬🇧": CountryCodeAndName("GB", "United Kingdom"),
    "🇬🇩": CountryCodeAndName("GD", "Grenada"),
    "🇬🇪": CountryCodeAndName("GE", "Georgia"),
    "🇬🇫": CountryCodeAndName("GF", "French Guiana"),
    "🇬🇬": CountryCodeAndName("GG", "Guernsey"),
    "🇬🇭": CountryCodeAndName("GH", "Ghana"),
    "🇬🇮": CountryCodeAndName("GI", "Gibraltar"),
    "🇬🇱": CountryCodeAndName("GL", "Greenland"),
    "🇬🇲": CountryCodeAndName("GM", "Gambia"),
    "🇬🇳": CountryCodeAndName("GN", "Guinea"),
    "🇬🇵": CountryCodeAndName("GP", "Guadeloupe"),
    "🇬🇶": CountryCodeAndName("GQ", "Equatorial Guinea"),
    "🇬🇷": CountryCodeAndName("GR", "Greece"),
    "🇬🇸": CountryCodeAndName("GS", "South Georgia & South Sandwich Islands"),
    "🇬🇹": CountryCodeAndName("GT", "Guatemala"),
    "🇬🇺": CountryCodeAndName("GU", "Guam"),
    "🇬🇼": CountryCodeAndName("GW", "Guinea-Bissau"),
    "🇬🇾": CountryCodeAndName("GY", "Guyana"),
    "🇭🇰": CountryCodeAndName("HK", "Hong Kong SAR China"),
    "🇭🇲": CountryCodeAndName("HM", "Heard & McDonald Islands"),
    "🇭🇳": CountryCodeAndName("HN", "Honduras"),
    "🇭🇷": CountryCodeAndName("HR", "Croatia"),
    "🇭🇹": CountryCodeAndName("HT", "Haiti"),
    "🇭🇺": CountryCodeAndName("HU", "Hungary"),
    "🇮🇩": CountryCodeAndName("ID", "Indonesia"),
    "🇮🇪": CountryCodeAndName("IE", "Ireland"),
    "🇮🇱": CountryCodeAndName("IL", "Israel"),
    "🇮🇲": CountryCodeAndName("IM", "Isle of Man"),
    "🇮🇳": CountryCodeAndName("IN", "India"),
    "🇮🇴": CountryCodeAndName("IO", "British Indian Ocean Territory"),
    "🇮🇶": CountryCodeAndName("IQ", "Iraq"),
    "🇮🇷": CountryCodeAndName("IR", "Iran"),
    "🇮🇸": CountryCodeAndName("IS", "Iceland"),
    "🇮🇹": CountryCodeAndName("IT", "Italy"),
    "🇯🇪": CountryCodeAndName("JE", "Jersey"),
    "🇯🇲": CountryCodeAndName("JM", "Jamaica"),
    "🇯🇴": CountryCodeAndName("JO", "Jordan"),
    "🇯🇵": CountryCodeAndName("JP", "Japan"),
    "🇰🇪": CountryCodeAndName("KE", "Kenya"),
    "🇰🇬": CountryCodeAndName("KG", "Kyrgyzstan"),
    "🇰🇭": CountryCodeAndName("KH", "Cambodia"),
    "🇰🇮": CountryCodeAndName("KI", "Kiribati"),
    "🇰🇲": CountryCodeAndName("KM", "Comoros"),
    "🇰🇳": CountryCodeAndName("KN", "St. Kitts & Nevis"),
    "🇰🇵": CountryCodeAndName("KP", "North Korea"),
    "🇰🇷": CountryCodeAndName("KR", "South Korea"),
    "🇰🇼": CountryCodeAndName("KW", "Kuwait"),
    "🇰🇾": CountryCodeAndName("KY", "Cayman Islands"),
    "🇰🇿": CountryCodeAndName("KZ", "Kazakhstan"),
    "🇱🇦": CountryCodeAndName("LA", "Laos"),
    "🇱🇧": CountryCodeAndName("LB", "Lebanon"),
    "🇱🇨": CountryCodeAndName("LC", "St. Lucia"),
    "🇱🇮": CountryCodeAndName("LI", "Liechtenstein"),
    "🇱🇰": CountryCodeAndName("LK", "Sri Lanka"),
    "🇱🇷": CountryCodeAndName("LR", "Liberia"),
    "🇱🇸": CountryCodeAndName("LS", "Lesotho"),
    "🇱🇹": CountryCodeAndName("LT", "Lithuania"),
    "🇱🇺": CountryCodeAndName("LU", "Luxembourg"),
    "🇱🇻": CountryCodeAndName("LV", "Latvia"),
    "🇱🇾": CountryCodeAndName("LY", "Libya"),
    "🇲🇦": CountryCodeAndName("MA", "Morocco"),
    "🇲🇨": CountryCodeAndName("MC", "Monaco"),
    "🇲🇩": CountryCodeAndName("MD", "Moldova"),
    "🇲🇪": CountryCodeAndName("ME", "Montenegro"),
    "🇲🇫": CountryCodeAndName("MF", "St. Martin"),
    "🇲🇬": CountryCodeAndName("MG", "Madagascar"),
    "🇲🇭": CountryCodeAndName("MH", "Marshall Islands"),
    "🇲🇰": CountryCodeAndName("MK", "North Macedonia"),
    "🇲🇱": CountryCodeAndName("ML", "Mali"),
    "🇲🇲": CountryCodeAndName("MM", "Myanmar (Burma)"),
    "🇲🇳": CountryCodeAndName("MN", "Mongolia"),
    "🇲🇴": CountryCodeAndName("MO", "Macao SAR China"),
    "🇲🇵": CountryCodeAndName("MP", "Northern Mariana Islands"),
    "🇲🇶": CountryCodeAndName("MQ", "Martinique"),
    "🇲🇷": CountryCodeAndName("MR", "Mauritania"),
    "🇲🇸": CountryCodeAndName("MS", "Montserrat"),
    "🇲🇹": CountryCodeAndName("MT", "Malta"),
    "🇲🇺": CountryCodeAndName("MU", "Mauritius"),
    "🇲🇻": CountryCodeAndName("MV", "Maldives"),
    "🇲🇼": CountryCodeAndName("MW", "Malawi"),
    "🇲🇽": CountryCodeAndName("MX", "Mexico"),
    "🇲🇾": CountryCodeAndName("MY", "Malaysia"),
    "🇲🇿": CountryCodeAndName("MZ", "Mozambique"),
    "🇳🇦": CountryCodeAndName("NA", "Namibia"),
    "🇳🇨": CountryCodeAndName("NC", "New Caledonia"),
    "🇳🇪": CountryCodeAndName("NE", "Niger"),
    "🇳🇫": CountryCodeAndName("NF", "Norfolk Island"),
    "🇳🇬": CountryCodeAndName("NG", "Nigeria"),
    "🇳🇮": CountryCodeAndName("NI", "Nicaragua"),
    "🇳🇱": CountryCodeAndName("NL", "Netherlands"),
    "🇳🇴": CountryCodeAndName("NO", "Norway"),
    "🇳🇵": CountryCodeAndName("NP", "Nepal"),
    "🇳🇷": CountryCodeAndName("NR", "Nauru"),
    "🇳🇺": CountryCodeAndName("NU", "Niue"),
    "🇳🇿": CountryCodeAndName("NZ", "New Zealand"),
    "🇴🇲": CountryCodeAndName("OM", "Oman"),
    "🇵🇦": CountryCodeAndName("PA", "Panama"),
    "🇵🇪": CountryCodeAndName("PE", "Peru"),
    "🇵🇫": CountryCodeAndName("PF", "French Polynesia"),
    "🇵🇬": CountryCodeAndName("PG", "Papua New Guinea"),
    "🇵🇭": CountryCodeAndName("PH", "Philippines"),
    "🇵🇰": CountryCodeAndName("PK", "Pakistan"),
    "🇵🇱": CountryCodeAndName("PL", "Poland"),
    "🇵🇲": CountryCodeAndName("PM", "St. Pierre & Miquelon"),
    "🇵🇳": CountryCodeAndName("PN", "Pitcairn Islands"),
    "🇵🇷": CountryCodeAndName("PR", "Puerto Rico"),
    "🇵🇸": CountryCodeAndName("PS", "Palestinian Territories"),
    "🇵🇹": CountryCodeAndName("PT", "Portugal"),
    "🇵🇼": CountryCodeAndName("PW", "Palau"),
    "🇵🇾": CountryCodeAndName("PY", "Paraguay"),
    "🇶🇦": CountryCodeAndName("QA", "Qatar"),
    "🇷🇪": CountryCodeAndName("RE", "Réunion"),
    "🇷🇴": CountryCodeAndName("RO", "Romania"),
    "🇷🇸": CountryCodeAndName("RS", "Serbia"),
    "🇷🇺": CountryCodeAndName("RU", "Russia"),
    "🇷🇼": CountryCodeAndName("RW", "Rwanda"),
    "🇸🇦": CountryCodeAndName("SA", "Saudi Arabia"),
    "🇸🇧": CountryCodeAndName("SB", "Solomon Islands"),
    "🇸🇨": CountryCodeAndName("SC", "Seychelles"),
    "🇸🇩": CountryCodeAndName("SD", "Sudan"),
    "🇸🇪": CountryCodeAndName("SE", "Sweden"),
    "🇸🇬": CountryCodeAndName("SG", "Singapore"),
    "🇸🇭": CountryCodeAndName("SH", "St. Helena"),
    "🇸🇮": CountryCodeAndName("SI", "Slovenia"),
    "🇸🇯": CountryCodeAndName("SJ", "Svalbard & Jan Mayen"),
    "🇸🇰": CountryCodeAndName("SK", "Slovakia"),
    "🇸🇱": CountryCodeAndName("SL", "Sierra Leone"),
    "🇸🇲": CountryCodeAndName("SM", "San Marino"),
    "🇸🇳": CountryCodeAndName("SN", "Senegal"),
    "🇸🇴": CountryCodeAndName("SO", "Somalia"),
    "🇸🇷": CountryCodeAndName("SR", "Suriname"),
    "🇸🇸": CountryCodeAndName("SS", "South Sudan"),
    "🇸🇹": CountryCodeAndName("ST", "São Tomé & Príncipe"),
    "🇸🇻": CountryCodeAndName("SV", "El Salvador"),
    "🇸🇽": CountryCodeAndName("SX", "Sint Maarten"),
    "🇸🇾": CountryCodeAndName("SY", "Syria"),
    "🇸🇿": CountryCodeAndName("SZ", "Eswatini"),
    "🇹🇨": CountryCodeAndName("TC", "Turks & Caicos Islands"),
    "🇹🇩": CountryCodeAndName("TD", "Chad"),
    "🇹🇫": CountryCodeAndName("TF", "French Southern Territories"),
    "🇹🇬": CountryCodeAndName("TG", "Togo"),
    "🇹🇭": CountryCodeAndName("TH", "Thailand"),
    "🇹🇯": CountryCodeAndName("TJ", "Tajikistan"),
    "🇹🇰": CountryCodeAndName("TK", "Tokelau"),
    "🇹🇱": CountryCodeAndName("TL", "Timor-Leste"),
    "🇹🇲": CountryCodeAndName("TM", "Turkmenistan"),
    "🇹🇳": CountryCodeAndName("TN", "Tunisia"),
    "🇹🇴": CountryCodeAndName("TO", "Tonga"),
    "🇹🇷": CountryCodeAndName("TR", "Türkiye"),
    "🇹🇹": CountryCodeAndName("TT", "Trinidad & Tobago"),
    "🇹🇻": CountryCodeAndName("TV", "Tuvalu"),
    "🇹🇼": CountryCodeAndName("TW", "Taiwan"),
    "🇹🇿": CountryCodeAndName("TZ", "Tanzania"),
    "🇺🇦": CountryCodeAndName("UA", "Ukraine"),
    "🇺🇬": CountryCodeAndName("UG", "Uganda"),
    "🇺🇲": CountryCodeAndName("UM", "U.S. Outlying Islands"),
    "🇺🇸": CountryCodeAndName("US", "United States"),
    "🇺🇾": CountryCodeAndName("UY", "Uruguay"),
    "🇺🇿": CountryCodeAndName("UZ", "Uzbekistan"),
    "🇻🇦": CountryCodeAndName("VA", "Vatican City"),
    "🇻🇨": CountryCodeAndName("VC", "St. Vincent & Grenadines"),
    "🇻🇪": CountryCodeAndName("VE", "Venezuela"),
    "🇻🇬": CountryCodeAndName("VG", "British Virgin Islands"),
    "🇻🇮": CountryCodeAndName("VI", "U.S. Virgin Islands"),
    "🇻🇳": CountryCodeAndName("VN", "Vietnam"),
    "🇻🇺": CountryCodeAndName("VU", "Vanuatu"),
    "🇼🇫": CountryCodeAndName("WF", "Wallis & Futuna"),
    "🇼🇸": CountryCodeAndName("WS", "Samoa"),
    "🇽🇰": CountryCodeAndName("XK", "Kosovo"),
    "🇾🇪": CountryCodeAndName("YE", "Yemen"),
    "🇾🇹": CountryCodeAndName("YT", "Mayotte"),
    "🇿🇦": CountryCodeAndName("ZA", "South Africa"),
    "🇿🇲": CountryCodeAndName("ZM", "Zambia"),
    "🇿🇼": CountryCodeAndName("ZW", "Zimbabwe"),
  };
}
